# Generated by Django 4.2.7 on 2025-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="auth_provider",
            field=models.CharField(
                choices=[("password", "Password"), ("google", "Google")],
                default="password",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("customer", "Customer")],
                default="admin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
