# Generated by Django 4.2.7 on 2025-09-07 10:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("flat", "Flat/Apartment"),
                            ("house", "House/Villa"),
                            ("plot", "Plot"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("For Sale", "For Sale"), ("For Rent", "For Rent")],
                        max_length=20,
                    ),
                ),
                ("price", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                (
                    "area",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("bedrooms", models.CharField(default="N/A", max_length=10)),
                ("bathrooms", models.CharField(default="N/A", max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("amenities", models.TextField(blank=True, null=True)),
                ("owner_name", models.CharField(blank=True, max_length=100, null=True)),
                ("owner_phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "owner_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "db_table": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_images",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
    ]
