# Generated by Django 4.2.7 on 2025-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_propertyimage_image_url_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
