# Generated by Django 4.2.7 on 2025-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pincode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pincode",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("area", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Pincodes",
                "db_table": "pincodes",
                "ordering": ["pincode"],
            },
        ),
    ]
