# Generated by Django 4.2.7 on 2025-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_category_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
