# Generated by Django 4.2.7 on 2025-11-16 16:16

import django.core.validators
import re
from django.db import migrations, models


def convert_price_to_integer(apps, schema_editor):
    """Convert price strings to integers"""
    Property = apps.get_model('properties', 'Property')
    
    for property_obj in Property.objects.all():
        if property_obj.price:
            price_str = str(property_obj.price)
            # Remove currency symbols and spaces
            price_str = price_str.replace('₹', '').replace(',', '').replace(' ', '').strip()
            
            # Handle "Cr" (crores) - multiply by 10000000
            if 'cr' in price_str.lower():
                price_str = price_str.lower().replace('cr', '').strip()
                try:
                    price_value = float(price_str) * 10000000
                    property_obj.price_new = int(price_value)
                except (ValueError, TypeError):
                    property_obj.price_new = 0
            # Handle "L" or "Lakh" - multiply by 100000
            elif 'l' in price_str.lower() or 'lakh' in price_str.lower():
                price_str = price_str.lower().replace('l', '').replace('lakh', '').strip()
                try:
                    price_value = float(price_str) * 100000
                    property_obj.price_new = int(price_value)
                except (ValueError, TypeError):
                    property_obj.price_new = 0
            else:
                # Try to extract number
                numbers = re.findall(r'\d+', price_str)
                if numbers:
                    try:
                        property_obj.price_new = int(''.join(numbers))
                    except (ValueError, TypeError):
                        property_obj.price_new = 0
                else:
                    property_obj.price_new = 0
        else:
            property_obj.price_new = 0
        property_obj.save(update_fields=['price_new'])


def reverse_convert_price(apps, schema_editor):
    """Reverse conversion - convert integers back to strings"""
    Property = apps.get_model('properties', 'Property')
    for property_obj in Property.objects.all():
        if property_obj.price_new:
            # Convert back to string format (simplified)
            if property_obj.price_new >= 10000000:
                property_obj.price = f"₹{property_obj.price_new / 10000000:.2f} Cr"
            elif property_obj.price_new >= 100000:
                property_obj.price = f"₹{property_obj.price_new / 100000:.2f} L"
            else:
                property_obj.price = f"₹{property_obj.price_new:,}"
        else:
            property_obj.price = "₹0"
        property_obj.save(update_fields=['price'])


def convert_area_to_carpet_area(apps, schema_editor):
    """Convert old area field to carpet_area"""
    Property = apps.get_model('properties', 'Property')
    for property_obj in Property.objects.all():
        if hasattr(property_obj, 'area') and property_obj.area:
            property_obj.carpet_area = property_obj.area
            property_obj.save(update_fields=['carpet_area'])


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_city_activation_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "db_table": "amenities",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="property",
            name="amenities",
        ),
        migrations.AddField(
            model_name="property",
            name="buildup_area",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Buildup area in sq ft",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="carpet_area",
            field=models.PositiveIntegerField(
                default=1000,
                help_text="Carpet area in sq ft",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in feet (for buildings)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in feet",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in feet",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price_new",
            field=models.BigIntegerField(
                default=0,
                help_text="Price in rupees (integer)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RunPython(convert_price_to_integer, reverse_convert_price),
        migrations.RemoveField(
            model_name="property",
            name="price",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="price_new",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="property",
            name="area",
        ),
        migrations.RunPython(convert_area_to_carpet_area, migrations.RunPython.noop),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="properties", to="properties.amenity"
            ),
        ),
    ]
